gen/gen.go
gen/nodejs/hil.go
il/binder_hil.go

And detect and fail on circular dependencies. Because Terraform allows
circular dependencies between modules so long as the elaborated graph
does not contain actual circular dependencies, we will need to adjust
this strategy in the long term.

Add support for a few more functions.

---

gen/nodejs/generator.go
il/boundTree_visitor.go

Specifically, do not import modules like fs, process, etc. if they are
not required by the generated code.

Only import required modules.

---

gen/nodejs/properties.go
il/binder_hil.go

- Allow references to count.index even if there is no count in scope,
which is the case for uncounted resources. Resolve these references to
a literal "1.0".
- Format single-item lists more densely.

Two small fixes

---

gen/nodejs/generator.go
il/binder_hil.go
il/binder_properties.go
il/boundTree.go
il/boundTree_visitor.go
il/graph.go
main.go
tests/terraform/aws/cognito-user-pool/main.tf

These changes allow the binder to tolerate the absence of resource
provider plugins. The code generated for a resource that has no plugin
information may be incorrect: in particular, property types and names
will not be available, so any mappings that differ based on that
information will be off.
This behavior is disabled by default, and can be enabled by passing the
`--allow-missing-plugins` flag when invoking `tf2pulumi`.

Tolerate missing plugins

---

convert/convert.go
gen/nodejs/archive.go
gen/nodejs/generator.go
gen/nodejs/hil.go
gen/nodejs/http.go
gen/nodejs/properties.go
main.go

This changes a few things to make this code usable from within
a library, in addition to its existing CLI form:
* Move setup logic into a new package, convert
* Add options to control the existing flags behavior (ignoring
missing plugins), the source path to read Terraform modules
from, and the destination writer for the converted code
* Replace all fmt.Print* writes with calls to the custom writer
I am doing this as part of an experiment to leverage this library
in our pulumi-terraform bridge's document generation.

Refactor to make library-friendly

---

Gopkg.lock
gen/nodejs/generator.go
il/boundTree_visitor.go
il/rewriters.go
tests/terraform/aws/aws_test.go
tests/terraform/aws/lb-listener/.gitignore
tests/terraform/aws/lb-listener/Pulumi.yaml
tests/terraform/aws/lb-listener/index.base.ts
tests/terraform/aws/lb-listener/main.tf
tests/terraform/aws/lb-listener/package.json
tests/terraform/aws/lb-listener/tsconfig.json
tests/terraform/tests.go

Module imports previously got emitted in a non-deterministic order.
This change sorts them by name to ensure determinism. Part of the
fixes required for pulumi/tf2pulumi#32.

Emit module imports in a stable order

---

convert/convert.go
il/graph.go
il/plugin_info.go
main.go

- Allow users of the convert package to specify a source for plugin
information
- Allow users of the convert package to specify a logger to use for
diagnostic information
- Simplify the plugin information source interface

Clean up some rough edges for library use

---

Gopkg.lock
il/graph.go

Allow the input configuration to refer to resources that do not exist in
the provider's schema information. This can occur for a couple reasons:
- The version of the provider expected by the configuration does not
match the version of the provider described by the schema
- The input configuration has a bug

Tolerate missing resources

---

CONTRIBUTING.md
Makefile

This target builds .tar.gz files that are appropriate for uploading as
part of a GitHub Release.

Add a `release` target to the Makefile

---

gen/nodejs/generator.go
gen/nodejs/generator_test.go
gen/nodejs/properties.go

The first cut of the code responsible for turning arbitrary TF names
into valid JavaScript identifiers was woefully incomplete. These changes
reimplement that code to confrom with the ECMA-262 spec.
Fixes #28.

Fix identifier generation

---

gen/nodejs/generator.go
gen/nodejs/generator_test.go
gen/nodejs/hil.go
gen/nodejs/hil_test.go
gen/nodejs/lower.go

Instead of generating plain string literals with escaped newlines,
generate template literals with literal newlines.
Also, lower certain path variables to bound literals prior to code
generation in order to avoid the silliness of string literals inside
interpolations in template literals.
Fixes #30.

Improve string literal generation

---

gen/nodejs/generator.go
gen/nodejs/hil.go
gen/nodejs/hil_test.go
il/coercions.go
il/coercions_test.go
tests/terraform/aws/lb-listener/index.base.ts

Implement a "good enough" version of ECMA-262's `Number.parseFloat` and
use it to statically coerce string literals to numbers where necessary.
Also, improve numeric literal generation to use only as many significant
digits as are necessary to uniquely identify the number.
Fixes #55.

Statically coerce string literals to numbers

---

Gopkg.lock
convert/convert.go
gen/nodejs/archive.go
gen/nodejs/generator.go
gen/nodejs/generator_test.go
gen/nodejs/http.go
gen/nodejs/properties.go
il/boundTree.go
il/graph.go
il/graph_comments.go
il/graph_comments_test.go
main.go

These changes implement basic extraction of comments from a module's HCL
source file. Any IL node may have leading and trailing comments attached
to it. The NodeJS generator has been updated to convert leading comments
for all top-level entities and map and list elements.
Fixes #34.

Extract comments from HCL

---

gen/nodejs/archive.go
gen/nodejs/assign_names.go
gen/nodejs/assign_names_test.go
gen/nodejs/generator.go
gen/nodejs/generator_test.go
gen/nodejs/hil.go
gen/nodejs/http.go
tests/terraform/aws/lb-listener/index.base.ts

Rather than generating simple, ugly, and ~probably unique names for
top-level nodes, assign the "nicest" names possible that are guaranteed
to be legal and unambiguous. The algorithm works like so:
- Assign names to outputs, locals, variables, and modules in that order.
- Outputs are never ambiguous, as they are assigned first and are
guaranteed to be unique in HCL
- If a local is ambiguous, attempt to disambiguate by prepending "my"
- If a variable is ambiguous, attempt to disambiguate by appending
"Input"
- If a module is ambiguous, attempt to disambiguate by appending
"Instance"
- If the name remains ambiguous, append an increasing integer
starting at 1 until it is no longer ambiguous.
- Assign resource names.
- If the resource's name is a single character, pretend it has no
name and …

Improve top-level name generation

---

gen/nodejs/assign_names_apply.go
gen/nodejs/assign_names_test.go
gen/nodejs/generator.go
gen/nodejs/hil.go
tests/terraform/aws/lb-listener/index.base.ts

Rather than using `__argX`, derive the name for each apply argument from
the name of its corresponding variable reference.

Assign nicer names for apply args

---

convert/convert.go
gen/nodejs/hil.go
il/rewriters.go
main.go
tests/terraform/aws/asg/main.tf
tests/terraform/aws/aws_test.go
tests/terraform/aws/cognito-user-pool/main.tf
tests/terraform/aws/count/main.tf
tests/terraform/aws/ecs-alb/main.tf
tests/terraform/aws/eip/main.tf
tests/terraform/aws/elb/main.tf
tests/terraform/aws/lambda/main.tf
tests/terraform/tests.go

Our providers commonly support auto-naming resources if a name is not
specified in order to help avoid name collisions. These changes add a
flag to `tf2pulumi` that can be used to specify the key of a name
property to filter from all resources in order to allow the autonamer to
go to work.
Fixes #43.

Add support for filtering resource names

---

CHANGELOG.md
gen/nodejs/hil.go
il/binder_hil.go

- Support `terraform.workspace` references. The moral equivalent of the
Terraform workspace name is the Pulumi stack name, so these turn into
`pulumi.getStack()`.
- Allow non-splat/indexed access to counted resources. This is allowed
in Terraform when the count evaluates to 1.
Fixes #68.

Fix two binding issues

---

CHANGELOG.md
gen/nodejs/generator.go
gen/nodejs/hil.go
il/boundTree.go
il/boundTree_visitor.go

Data sources with output-typed inputs need to be generated as a call to
`apply` that contains a call to the data source itself with the resolved
outputs. These changes implement this in a moderately subtle fashion:
instead of generating the data source ad-hoc, it is turned into an
intrinsic that is then handed over to the apply rewriter. If the apply
rewriter does not transform the intrinsic, the call to the data source
is wrapped in a call to `pulumi.output` in order to keep the generated
code in normal form.
Fixes #67.

Fix data sources with output-typed inputs

---

convert/convert.go
gen/python/generator.go
main.go

This commit adds a skeleton backend for Python that does nothing. It
hooks up the relevant plumbing bits in the frontend to select Python as
a target language and generate a Python generator if requested. The
backend basically does nothing and emits NYIs for everything.
Future commits will incrementally build up the Python backend.

Add skeleton for Python backend

---

gen/nodejs/assign_names_apply.go
gen/nodejs/assign_names_test.go
gen/nodejs/generator.go
gen/nodejs/hil.go
gen/nodejs/intrinsics.go
gen/nodejs/intrinsics_test.go
il/binder_hil.go
il/coercions.go
il/intrinsics.go
il/intrinsics_test.go
il/rewriters.go

The intent of these helpers is to make working with intrinsic calls more
reliable and more convenient. The general approach is to add three
constructs for a particular intrinsic:
1. A constant to represent the intrinsic's name
2. A factory function to create calls to the intrinsic
3. A parser function that extracts the relevant values from the
intrinsic

Add intrinsic helpers

---

tests/terraform/aws/aws_test.go
tests/terraform/tests.go

In anticipation of a Python backend, this commit beefs up the integration test harness a little bit to be able to run tests against multiple targets simultaneously without having to explicitly do it as part of the test definition.
This PR also contains a limited "sugar" around the test harness which presents a fluent-ish interface for defining and running tests. The sugary interface cuts down on a lot of boilerplate code needed to write and run a tf2pulumi test, so I think it's a usability win (since I'm planning to bring up new tests as I bring up Python), but I'll defer to Pat's thoughts on aesthetics.
Worth noting is that the integration test framework is now configured to run all tests with the Python backend, although every test explicitly skips Python because the Python backend …

 Augment integration test harness

---

CHANGELOG.md
Gopkg.lock
convert/convert.go
main.go

If `--filter-auto-names` is specified on the command line, filter
values for properties that are marked as autogenerated names from
the generated code.

Use schema information to elide autonames

---

gen/emit.go
gen/nodejs/archive.go
gen/nodejs/generator.go
gen/nodejs/generator_test.go
gen/nodejs/hil.go
gen/nodejs/http.go
gen/nodejs/intrinsics.go
gen/nodejs/properties.go
il/boundTree.go
il/boundTree_visitor.go

Move these methods into a utility type in the gen package. This will
allow a little bit more code sharing between the NodeJS and Python
backends.

Refactor genf and friends

---

CHANGELOG.md
convert/convert.go
gen/emit.go
gen/nodejs/generator.go
gen/nodejs/generator_test.go
gen/nodejs/hil.go
gen/nodejs/intrinsics.go
gen/nodejs/lower.go
go.mod
main.go
tests/terraform/aws/ec2/index.base.ts

There are two major changes here:
1. Generate normal property access expressions for `apply` calls that
can be handled by proxy. This is exactly the set of applies that look
like `r.prop.apply(p => p.nested)`. When enabled, these will be
emitted as `r.prop.nested`.
2. Generate calls to `pulumi.interpolate` for applies that involve the
interpolation of multiple properties and literals. This is the set of
applies that look like ```r.prop.apply(p => `foo: ${p}` ``` or
```pulumi.all([r.foo, s.bar]).apply(([f, b]) => `f: ${f}, b: ${b}`)```.
These will be emitted as ```pulumi.interpolate`foo: ${r.prop}` ``` and
```pulumi.interpolate`f: ${r.foo}, b: ${s.bar}` ```, respectively.
These features can be disabled by setting the target SDK version to
anything below 0.17.0 using the …

Lower proxied applies.

---

CHANGELOG.md
gen/nodejs/hil.go
gen/nodejs/lower.go
go.mod
il/schemas.go
tests/terraform/gcp/gcp_test.go
tests/terraform/gcp/record_set/Pulumi.yaml
tests/terraform/gcp/record_set/index.base.ts
tests/terraform/gcp/record_set/main.tf
tests/terraform/gcp/record_set/package.json
tests/terraform/gcp/record_set/tsconfig.json

- Properly fetch list element schemas when `il.Schema.PropertySchemas`
is invoked with an integer key
- Do not generate lifted property accesses for accesses that involve
array indexes, as array index expressions cannot be lifted
- Handle optional fields by generating a `!` expression
Fixes #113.

Fix a few array- and optional-related bugs.

---

CHANGELOG.md
convert/convert.go
gen/nodejs/testdata/test_ordering/index.ts
il/boundTree.go
il/graph.go
il/graph_comments.go
il/graph_comments_test.go
main.go
tests/terraform/aws/ec2/index.base.ts
tests/terraform/aws/lb-listener/index.base.ts
tests/terraform/gcp/record_set/index.base.ts
tests/terraform/tests.go

Add a leading comment to each top-level node that records the location of its original definition in the source TF config. This feature must be enabled by passing the `-record-locations` flag on the command line.

Annotate generated code with source locations.

---

gen/nodejs/assign_names.go
gen/nodejs/assign_names_test.go
gen/nodejs/generator.go

If a resource/provider/etc. name collides with the name of an import,
perform the usual disambiguation.

Disambiguate names that collide with imports.

---

CHANGELOG.md
gen/nodejs/generator.go
gen/nodejs/generator_test.go
gen/nodejs/hil.go
gen/nodejs/testdata/test_conditionals/index.ts
gen/nodejs/testdata/test_conditionals/main.tf
il/binder_hil.go
il/boundTree.go
il/rewriters.go

Conditionally-instantiated resources are now generated using `if`
statements rather than `for` loops. For most resources, the generated
code is as simple as:
```
let foo: Foo | undefined;
if (condition) {
foo = new Foo(...);
}
```
For resources with properties that reference the condition variable,
the code generation is a little bit more complicated. In this case, we
assign the result of the condition to a local so that the resource has
something to reference:
```
const createFoo = condition;
let foo: Foo | undefined;
if (createFoo) {
foo = new Foo(...);
}
```
Fixes #123.

Add support for generating conditional resources.

---

CHANGELOG.md
gen/gen.go
gen/gen_test.go
gen/nodejs/testdata/test_comments/index.16.ts
gen/nodejs/testdata/test_comments/index.17.ts
gen/nodejs/testdata/test_comments/index.v1.ts
gen/nodejs/testdata/test_conditionals/index.ts
gen/testdata/test_gen_order/index.ts
gen/testdata/test_gen_order/outputs.tf
gen/testdata/test_gen_order/security_group.tf
gen/testdata/test_gen_order/subnet.tf
gen/testdata/test_gen_order/variables.tf
il/graph.go
il/graph_comments.go
tests/terraform/aws/lb-listener/index.base.ts

Rather than generating nodes in order by kind and then alphabetically by
name, implement a new algorithm that attempts to keep definitions
grouped by source file.
This algorithm works by building a worklist of files to generate and
iterating until the worklist is empty. On each iteration, the nodes from
the file with the the fewest references to nodes that have not yet been
generated and that are defined in other files is chosen for generation.
Within each file, nodes are ordered by their appearence in the original
source file. Out-of-order generation only occurs when it is necessary to
satisfy the requirement that nodes are generated in a valid topological
order.

Improve generation order.

---

CHANGELOG.md
gen/nodejs/generator.go
gen/nodejs/generator_test.go
gen/nodejs/testdata/test_meta_properties/index.ts
gen/nodejs/testdata/test_meta_properties/main.tf
il/binder_hil.go
il/graph.go
il/graph_test.go
il/testdata/test_meta_properties/main.tf

- Custom timeouts are pulled verbatim from the `timeouts` property if it is present.
This works because we use the same names (`create`, `update`, `delete`) for our
own custom timeouts option.
- Any `ignore_changes` list is converted into an equivalent list of ignored properties.
The most subtle aspect of this conversion is that Terraform accepts a key prefix
rather than a full key; we support this by expanding the last element of the key
by matching subproperties at the final level by prefix as well.

Add support for custom timeouts and ignore changes.

---

gen/nodejs/assign_names_test.go
gen/nodejs/generator.go
gen/nodejs/generator_test.go
gen/nodejs/hil.go
gen/nodejs/intrinsics.go
gen/nodejs/intrinsics_test.go
gen/nodejs/lower.go
gen/python/hil.go
gen/python/intrinsics.go
gen/python/rewriters.go
il/binder_hil.go
il/boundTree.go
il/intrinsics.go
il/intrinsics_test.go

Copy the information we need from these nodes onto the expression nodes
themselves. This eliminates the need for downstream code to understand
HIL syntax nodes.

Remove HIL nodes from bound expressions.

---

convert/convert.go
gen/nodejs/archive.go
gen/nodejs/assign_names.go
gen/nodejs/assign_names_apply.go
gen/nodejs/assign_names_test.go
gen/nodejs/generator.go
gen/nodejs/generator_test.go
gen/nodejs/hil.go
gen/nodejs/http.go
gen/nodejs/lower.go
gen/python/generator.go
il/graph.go
il/graph_config.go
il/rewriters.go
il/rewriters_test.go

- Remove the usage of module.Tree
- Stop exporting raw resource/local/variable/etc. config from IL nodes
With these changes, the core of the IL no longer depends on TF11. The
remaining use of TF11 types is `BoundVariableAccess.TFVar`. For the sake
of simplicity, this will likely switch to using the TF12 equivalent in
the future.

Remove the usage of raw TF11 config in IL.

---

CHANGELOG.md
README.md
misc/import/import.ts

Adds a helper script and some light docs on how to automatically import cloud resources from an existing `.tfstate` file.
Part of #46.

Partial support for importing from tfstate

---

CHANGELOG.md
README.md

The documentation hasn't been updated since the switch to Go
modules, so removing any references to dep and updating the required
build command

Update installation documentation

---

convert/convert.go
convert/tf12.go

Or do not log at all, if no logger is present.

Log to the configured logger.

---

.goreleaser.yml

A lot of our tools assume this format, so replacement amd64 -> arch

fix build arch in archive

---

il/plugin_info.go

Use an RWMutex to protect cache accesses and insertions. This allows the
cache to be safely used from multiple goroutines concurrently.

Concurrency-proof the info cache.

---

convert/convert.go
convert/tf12.go

Rather than using the default plugin-based info source, respect the info
source present in the options.
This speeds up tfgen for providers with large numbers of examples by
about 10x, since it makes proper use of the caching info source.

[tf12] Respect the provider info source option.

---

.github/workflows/codegen-test.yml
convert/tf11.go

'$' and '%' only need to be escaped if they immediately precede a '{'.
These changes also add downstream codegen testing.
Fixes https://github.com/pulumi/pulumi/issues/4776.

[tf11] Fix template escaping.

---

.github/workflows/codegen-test.yml
convert/tf11.go
convert/tf12.go

Use the `terraformToPulumiName` method to translate the names of nested
blocks from Terraform to Pulumi names.
Fixes #193.

[tf12] Translate nested block names.

---

il/graph.go

When fetching the schema for a resource, ensure that the TF schema
always contains an ID property with type string. Not including this can
lead to non-determinism.
Fixes #195.

[tf11] Ensure resources always have an ID.

---

convert/convert.go

If the --terraform-version 12 option is used, then print the
diagnostic messages from the terraform 0.12 parsing rather than the 0.11
parsing.

Show diagnostics from TF12 if using version 12

---

.github/workflows/master.yml

Master build is failing because we are running tests tht don't exist. https://github.com/pulumi/tf2pulumi/runs/1788342696

Remove deleted tests

---

tests/coverage-report/test/coverage_test.go
tests/terraform/aws/aws_test.go
tests/terraform/aws/ec2/__main__.base.py
tests/terraform/aws/ec2/index.base.ts
tests/terraform/aws/ec2/main.tf
tests/terraform/tests.go

Add a NoParallel test option and apply it to four AWS tests.
Fixes #247

tests: fix flakiness by reducing parallelism

---

README.md

Change the status badge in the README to use GitHub Actions instead of Travis.
It looks like we moved off Travis awhile ago. The badge was failing, and clicking on the badge results in a 404. This PR replaces the Travis status badge with a GitHub Actions badge instead.

Change badge from Travis to GitHub

---

.github/workflows/release.yml

Fixes publish by using a MacOS goreleaser agent, because there's a dependency (notify) that uses CGO on darwin that can't be cross-compiled from Linux.

Update release.yml to use macos runner
