pulumi/tf2pulumi

- .travis.yml
- Makefile
- gen/nodejs/generator.go
- il/binder_hil.go
- il/graph.go
- tests/terraform/aws/aws_test.go
- tests/terraform/aws/elb2/Pulumi.yaml
- tests/terraform/aws/elb2/main.tf
- tests/terraform/aws/elb2/package.json
- tests/terraform/aws/elb2/tsconfig.json
- tests/terraform/aws/elb2/userdata.sh
Instead of typing all local variables as `Unknown`, type them using the
type of their value. This is necessary for correct code generation.
>  Improve local variable typing.

- Makefile
- gen/nodejs/generator.go
- il/binder_properties.go
- il/graph.go
- main.go
- scripts/get-version
- version/version.go
> Include property names in binding errors

- README.md
Just removing an extra quote in install section
> Remove extra quote in readme

- Gopkg.template.toml
- Gopkg.toml
- Makefile
- il/binder_hil.go
- il/graph.go
- il/graph_test.go
- main.go
And improve the error experience for circular references.
Fixes #39.
> Handle forward local references

- .travis.yml
- gen/python/generator.go
- gen/python/hil.go
- gen/python/hil_test.go
- tests/terraform/random/random-integer/Pulumi.yaml
- tests/terraform/random/random-integer/__main__.base.py
- tests/terraform/random/random-integer/main.tf
- tests/terraform/random/random-integer/package.json
- tests/terraform/random/random-integer/tsconfig.json
- tests/terraform/random/random_test.go
- tests/terraform/tests.go
This commit contains the necessary plumbing to correctly convert simple Terraform resources into Python. As a milestone, this commit also contains a regression test using the Random provider that correctly converts and runs.
> Python: Basic Resources

- README.md
This was mentioned in the community chat today, so likely could use an additional pointer.
> Mention binary releases in README

- gen/python/generator.go
- gen/python/hil.go
- gen/python/intrinsics.go
- gen/python/rewriters.go
- tests/terraform/aws/aws_test.go
- tests/terraform/aws/ec2/.gitignore
- tests/terraform/aws/ec2/Pulumi.yaml
- tests/terraform/aws/ec2/__main__.base.py
- tests/terraform/aws/ec2/index.base.ts
- tests/terraform/aws/ec2/main.tf
Work in progress. Working through issues until a simple EC2 example fully translates.
> Python: Bring up EC2 example

- CHANGELOG.md
- convert/convert.go
- gen/nodejs/generator.go
- gen/nodejs/generator_test.go
- il/boundTree_visitor.go
- il/rewriters.go
- il/rewriters_test.go
- main.go
- tests/terraform/aws/ec2/index.base.ts
Just what it says on the tin. Only works for NodeJS for the time being.
Part of https://github.com/pulumi/home/issues/543.
> Optionally generate prompt datasource accesses.

- CHANGELOG.md
- build/common.mk
- gen/gen.go
- gen/nodejs/assign_names.go
- gen/nodejs/generator.go
- gen/nodejs/hil.go
- gen/nodejs/intrinsics.go
- gen/nodejs/intrinsics_test.go
- gen/python/generator.go
- il/binder_hil.go
- il/graph.go
- tests/terraform/aws/aws_test.go
- tests/terraform/aws/networking/region/variables.tf
- tests/terraform/aws/networking/subnet/variables.tf
Just what it says on the tin. Generate instantiations for non-default
providers and reference them appropriately.
> Support first-class providers for NodeJS.

- CHANGELOG.md
- gen/gen.go
- gen/nodejs/generator.go
- gen/nodejs/generator_test.go
- gen/nodejs/hil.go
- gen/nodejs/testdata/test_comments/index.16.ts
- gen/nodejs/testdata/test_comments/index.17.ts
- gen/nodejs/testdata/test_comments/index.v1.ts
- gen/nodejs/testdata/test_ordering/index.ts
- gen/nodejs/testdata/test_ordering/main.tf
- il/coercions.go
- il/coercions_test.go
- il/graph.go
- Fix ordering for resources and module instantiations with explicit
providers
- Support more coercions between literals by coercing through strings
- Do not generate empty argument bags for nilary data source invocations
> Make a handful of small fixes.

- CHANGELOG.md
- gen/nodejs/hil.go
Check the first and last characters of the replace pattern when checking
for a regex.
> Fix replace codegen.

- gen/nodejs/generator.go
- gen/nodejs/testdata/test_meta_properties/index.ts
- gen/nodejs/testdata/test_ordering/index.ts
Fixes https://github.com/pulumi/tf2pulumi/issues/156
> Better spacing for options bag

- .github/workflows/release.yml
- .gitignore
- .goreleaser.yml
Will run goreleaser (without publish) on all v.X tags
Fixes #165
> add goreleaser configuration & github action

- .github/workflows/release.yml
- .goreleaser.yml
- .travis.yml
- Makefile
> Prepare for releases with goreleaser

- .travis.yml
Exclude the tags because that's been switch to gha
> Buld tf2pulumi on more events

- go.mod
- go.sum
- il/plugin_info.go
This gives about a 10% speedup in tfgen for providers with large numbers
of examples.
> Deserialize plugin info with jsoniter.

- .goreleaser.yml
- README.md
> Publishing tf2pulumi to our homebrew tap

- .github/workflows/golangci-lint.yml
- .github/workflows/master.yml
- .github/workflows/pull-request.yml
- tests/terraform/aws/aws_test.go
- tests/terraform/tests.go
Combines several PRs to see if cumulatively they result in passing checks.
Fixes https://github.com/pulumi/tf2pulumi/issue/277
> Fix the build

- .github/workflows/master.yml
- .github/workflows/pull-request.yml
This theoretically should fix the broken test on master.
> Update Node to 14.x in CI

- .github/workflows/golangci-lint.yml
- .github/workflows/master.yml
- .github/workflows/pull-request.yml
This fixes the broken lint workflow on master - with this setup lint and Go versions match so it works.
> Update lint workflow
